packages:
    # all packages in direct subdirs of packages/
    - 'packages/*'
    # all webs in subdirs of components/
    - 'webs/**'
    # exclude packages that are inside test directories
    - '!**/test/**'
